(lang dune 2.8)

(using menhir 2.1)

(cram enable)

(package
 (name testsuite1))

(package
 (name testsuite2))

(package
 (name testsuite3))

(package
 (name testsuite4))

(package
 (name testsuite5))

(package
 (name testsuite6))
