  $ cat extended.diff
  diff --git a/Python/Lambda.opam b/Python/Python.opam
  similarity index 85%
  rename from Python/Lambda.opam
  rename to Python/Python.opam
  index 1bd9c9d..be3b42f 100644
  --- a/Python/Lambda.opam
  +++ b/Python/Python.opam
  @@ -1,11 +1,11 @@
   # This file is generated by dune, edit dune-project instead
   opam-version: "2.0"
   version: "0.1"
  -synopsis: "FIXME An interpreter for language"
  +synopsis: "FIXME An interpreter for Python"
   description:
     "FIXME. A longer description, for example, which are the most interesing features being supported, etc."
   license: "LGPL-3.0-or-later"
   homepage: "FIXME Homepage"
   bug-reports: "FIXME where to put bug reports about the code"
  $ cat extended.diff | ../review/parser.exe - -f Python/Python.opam -l 5
  Got something. It should be at 6 lines below from the first chunk header of file in diff

Currently not the all possible extension of headers are supported.
For example dissimilarity index is not. See https://git-scm.com/docs/diff-format for details
  $ cat << EOF | ../review/parser.exe - -f Python/Python.opam -l 3
  > diff --git a/Python/Lambda.opam b/Python/Python.opam
  > similarity index 85%
  > rename from Python/Lambda.opam
  > rename to Python/Python.opam
  > dissimilarity index <number>
  > index 1bd9c9d..be3b42f 100644
  > --- a/Python/Lambda.opam
  > +++ b/Python/Python.opam
  > @@ -1,4 +1,4 @@
  > -synopsis: "FIXME An interpreter for language"
  > +synopsis: "FIXME An interpreter for Python"
  >  description:
  >  homepage: "FIXME Homepage"
  >  bug-reports: "FIXME where to put bug reports about the code"
  > EOF
  Parsing failed: : end_of_input
  [1]
