name: setup-dune experiment 4.14

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - 'master'

env:
  OPAMCONFIRMLEVEL: unsafe-yes

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Use dune
        uses: ocaml-dune/setup-dune@v2
        with:
          display: progress
          workspace: dune-workspace.ci

      - name: Running tests in release...
        run: |
          which dune
          dune test --profile=release


      # - run: find . -type f -executable
      # - run: tree

      - name: Send coverage report to Coveralls
        if: false && (github.event_name != 'pull_request')
        run: |
          make coverage
          bisect-ppx-report send-to Coveralls --coverage-path $BISECT_DIR
        env:
          BISECT_DIR: /tmp/zanudacov
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}

      # - name: Build API documentation
      #   if: github.event_name != 'pull_request'
      #   run: |
      #     dune build @install -p reviewer,zanuda

      # - if: github.event_name != 'pull_request'
      #   run: dune install reviewer zanuda
      - run: dune b @install
      - run: dune install --verbose

      - if: github.event_name != 'pull_request'
        run: dune exec -- make odig
      - if: github.event_name != 'pull_request'
        run: echo "ODIG_DOC_LOC=$(dune exec -- odig cache path)/html" >> $GITHUB_ENV

      - name: Deploy API documentation
        if:  (github.event_name != 'pull_request')
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.ODIG_DOC_LOC }}
          keep_files: true
          destination_dir: api
